### ISSUE TITLE
Player not working 

### ISSUE THREAD

**Issue by KanhiyaBagda** [timroesner/TRVideoView#7]
I checked recently TRVideoView not working with youtube url (Url play on web) even i have copied url from web and pass directly but didn't work.
[https://www.youtube.com/watch?v=2DDk-1aLnm4&feature=youtu.be]
No error log .

**Comment by timroesner** [comment]
Sorry for the delayed response. The last tag where it says `&feature=youtu.be` is messing with the parsing of the URL.
We also just published a new version that might address your issue.
